### ISSUE TITLE
[FEATURE] - tailwindcss 4

### ISSUE THREAD

**Issue by 0xCucurbitaceae** [premieroctet/next-admin#573]
### Summary

Tailwind CSS v4 doesn't support presets, but uses CSS variables instead.

### Basic Example

The CSS file should contain smth like:

```css
@import "tailwindcss";
@source "../../node_modules/@premieroctet/next-admin/dist";

@theme inline{
  --color-nextadmin-primary: var(--color-indigo-500);
  --color-nextadmin-brand-subtle: var(--color-indigo-400);
  --color-nextadmin-brand-default: var(--color-indigo-500);
  --color-nextadmin-brand-emphasis: var(--color-indigo-700);
  --color-nextadmin-brand-inverted: var(--color-white);
  --color-nextadmin-brand-muted: var(--color-slate-100);

  --color-nextadmin-menu-background: var(--color-slate-50);
  --color-nextadmin-menu-color: var(--color-slate-500);
  --color-nextadmin-menu-muted: oklch(100% 0.01 270);
  --color-nextadmin-menu-emphasis: var(--color-indigo-700);

  --color-nextadmin-border-default: var(--color-slate-200);
  --color-nextadmin-border-strong: var(--color-slate-300);

  --color-nextadmin-background-default: var(--color-white);
  --color-nextadmin-background-subtle: var(--color-slate-50);
  --color-nextadmin-background-muted: var(--color-slate-100);
  --color-nextadmin-background-emphasis: var(--color-slate-200);

  --color-nextadmin-content-default: var(--color-gray-400);
  --color-nextadmin-content-subtle: var(--color-neutral-600);
  --color-nextadmin-content-emphasis: var(--color-slate-500);
  --color-nextadmin-content-inverted: var(--color-gray-700);

  --color-nextadmin-alert-info-background: var(--color-blue-50);
  --color-nextadmin-alert-info-content: var(--color-blue-800);
  --color-nextadmin-alert-success-background: var(--color-green-50);
  --color-nextadmin-alert-success-content: var(--color-green-800);
  --color-nextadmin-alert-error-background: var(--color-red-50);
  --color-nextadmin-alert-error-content: var(--color-red-800);
}

.dark {
  @theme inline {
    --color-nextadmin-primary: var(--color-indigo-500);
    --color-nextadmin-brand-subtle: var(--color-indigo-400);
    --color-nextadmin-brand-default: var(--color-indigo-500);
    --color-nextadmin-brand-emphasis: var(--color-indigo-700);
    --color-nextadmin-brand-inverted: var(--color-white);
    --color-nextadmin-brand-muted: var(--color-slate-50);

    --color-nextadmin-menu-background: var(--color-slate-800);
    --color-nextadmin-menu-color: var(--color-slate-300);
    --color-nextadmin-menu-muted: var(--color-slate-600);
    --color-nextadmin-menu-emphasis: var(--color-slate-200);

    --color-nextadmin-border-default: var(--color-slate-600);
    --color-nextadmin-border-strong: var(--color-slate-700);

    --color-nextadmin-background-default: var(--color-slate-900);
    --color-nextadmin-background-emphasis: var(--color-slate-800);
    --color-nextadmin-background-subtle: var(--color-slate-600);
    --color-nextadmin-background-muted: var(--color-slate-500);

    --color-nextadmin-content-default: var(--color-gray-300);
    --color-nextadmin-content-subtle: var(--color-neutral-200);
    --color-nextadmin-content-emphasis: var(--color-slate-400);
    --color-nextadmin-content-inverted: var(--color-slate-50);

    --color-nextadmin-alert-info-background: var(--color-slate-600);
    --color-nextadmin-alert-info-content: var(--color-sky-200);
    --color-nextadmin-alert-success-background: var(--color-slate-600);
    --color-nextadmin-alert-success-content: var(--color-green-400);
    --color-nextadmin-alert-error-background: var(--color-slate-600);
    --color-nextadmin-alert-error-content: var(--color-red-400);
  }
}
```
